plugins {
    id 'com.android.application'
}

android {
    namespace 'in.textcall.lab'
    compileSdk 35

    defaultConfig {
        applicationId 'in.textcall.lab'
        minSdk 29
        targetSdk 35
        versionCode 2
        versionName '0.2-privacy-safe'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
